name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    # runs-on: [self-hosted, dedicated]
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5

      - name: install
        run: |
          npm i

      - name: Install Dependencies
        run: gem install bundler -v 2.4.22 && bundle install

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.4.0'

      - name: Start RN Package
        run: |
          npm run start &> android_packager.log &

      - name: Build detox
        run: |
          npm run e2e:build:android:release

      - name: Run detox
        run: |
          npm run e2e:run:android:release
