name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    # runs-on: [self-hosted, dedicated]
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install
        run: |
          npm i

      - name: Start RN Package
        run: |
          npm run start &> android_packager.log &

      - name: Build detox
        run: |
          npm run e2e:build:android:release

      - name: Run detox
        run: |
          npm run e2e:run:android:release
